### ISSUE TITLE
Hardcode devel builds to be 0.epoch

### ISSUE THREAD

**Issue by jgrund** [whamcloud/Dockerfiles#15]
Right now our devel builds do `epoch.release`, where epoch is num seconds since midnight 1970.

Instead, do `0.epoch` so versions not built with `imlteam/copr` will be superior if intended.

**Comment by utopiabound** [comment]
I think release should be of the form "0.epoch" not 0-epoch

**Comment by jgrund** [comment]
oops, fixed.
